### ISSUE TITLE
Accessibility issues with player controls

### ISSUE THREAD

**Issue by arsimr16** [jwplayer/jwplayer-sdk-android-demo#105]
I got the demo running on a Samsung Galaxy S8 after applying the changes in [this PR](https://github.com/jwplayer/jwplayer-sdk-android-demo/pull/100).  All the controls seem to work fine when the voice assistant is turned off.  When I turn the voice assistant on, the player becomes extremely difficult to use.

In portrait mode:
    * I can tap the screen to view the controls, tap a control to see that it is in focus (marked by a blue border) and hear the role, but all the buttons do not do anything except for the initial play button and the repeat video button.
    * I can double tap and long press to see the 'About This Video' option, and I can select that, but then the close button does not work.

In landscape mode (which you can only get to by rotating the device):
    * The controls work, but they do not announce the role or show the blue border so you can see which button is focused.

**Comment by AmitaiB** [comment]
Hello @arsimr16 , I'll copy here my response to you from elsewhere so that it can be seen publicly.

* As it turns out, [Accessibility](https://www.android.com/accessibility/) support is not yet a feature of our Android SDK's default player controls.
* It is an outstanding Feature Request, however, and I know that Product is very keen to bring this into our offerings.
  * To that end, we are busy rewriting our SDKs from the ground up in a way that should support Android's out-of-the-box Accessibility features, like Voice Assistant/TalkBack navigation.
  * At that point, Product and the mobile team will be in a position to officially support (test, debug, and fix) accessibility features and issues.

Just to be clear, this is ongoing iterative software development, and please do not construe anything I say to be making a commitment or promise in the course of explaining where we stand right now.

In the meantime, the way forward on this requires you to implement a custom native UI that lends itself to TalkBack navigation. For a helpful reference to start you off on this process, try looking at our Best Practice App target [Demo Native Controls](https://github.com/jwplayer/jwplayer-android-best-practice-apps/tree/master/DemoNativeControls).

Best regards,

Amitai Blickstein
Support Engineer, Mobile SDKs
