### ISSUE TITLE
Demo app crashes

### ISSUE THREAD

**Issue by IamYou2** [jwplayer/jwplayer-sdk-android-demo#118]
Trying to implement the basic android sdk 4 JW Player in my app. 

`public class MainActivity extends AppCompatActivity {

    private JWPlayer mPlayer;
    private String url = MyApplication.getInstance().getConfig().getURL();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        new LicenseUtil().setLicenseKey(this, "##################");

        JWPlayerView playerView = findViewById(R.id.jwplayer);
        mPlayer = playerView.getPlayer();

        PlaylistItem playlistItem = new PlaylistItem.Builder()
                .file("https://###########.m3u8")
                .build();
        List<PlaylistItem> playlist = new ArrayList<>();
        playlist.add(playlistItem);
        PlayerConfig config = new PlayerConfig.Builder()
                .playlist(playlist)
                .build();

        mPlayer.setup(config);
    }

}`

The line where mPlayer is assigned crashes with "Activity cannot be cast to androidx.lifecycle.LifecycleOwner
        at com.jwplayer.pub.view.JWPlayerView.getPlayer." Does the demo need all of the lifecycle methods in order to run?

**Comment by nadim1044** [comment]
Hey, have you got the solution for this? I am also facing same issue

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We recommend you create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket). 

I believe this issue is resolved so that no action will be required. Please follow the links above for a quick and effective response to future problems.
