### ISSUE TITLE
Video streaming reload on full screen ?

### ISSUE THREAD

**Issue by ywj7931** [jwplayer/jwplayer-sdk-android-demo#13]
When I click full screen icon, my streaming will reload, is there anyway to immediately show the video without reloading?
I am using JW player in my fragment and my activity is fixed in portrait mode

**Comment by ywj7931** [comment]
Also, When I click fullscreen icon, the screen rotates, the fullscreen icon is still "go to fullscreen" icon, I click again, the view become larger, and then the icon become "exit fullscreen" icon, I click again to return to portrait mode

**Comment by RikHeijdens** [comment]
Hi @ywj7931, 

This happens because by default Android will restart an Activity when the orientation of the activity changes.

To prevent the activity from restarting you'll need to ignore orientation changes within your Activity's config. You can do this by setting the following in your `AndroidManifest.xml`:

```
        <activity
            android:name=".YourActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        </activity>
```

Please let me know if that solves your problem.

**Comment by ywj7931** [comment]
@RikHeijdens Thanks for replying, but I encounter another problem, after setting it to fullscreen, the rightmost screen is white stripe, same size as navigation bar.
Also, when I press back button on fullscreen mode, I go back to my main with landscape mode, i have set my activity as vertical orientation.

**Comment by RikHeijdens** [comment]
Are you using a `CoordinatorLayout` in your Activity?

You can customize the skin using CSS, check out our [developer guide](https://developer.jwplayer.com/sdk/android/docs/developer-guide/customization/css-skins/) for instructions on how to do that.
