### ISSUE TITLE
How to replay video after completing it

### ISSUE THREAD

**Issue by atkalpe** [jwplayer/jwplayer-sdk-android-demo#27]
I want to replay video after first video completion when pressed on refresh/replay icon in android.
How to do that ?

**Comment by GMSyrimis** [comment]
@atkalpe By default there's a replay icon at the end of the video that should behave as expected on  our latest SDK.

I'll be closing this thread as it is old at this point. If you do have an issue setting this up, please provide the following:

**Issue Summary:**

**JWP SDK Ver #:**

**OS Version:** 

**Device make & model:**

**IDE:**

**Video or Screenshots:** 

**Demo App source code experiencing the issue:** 

**Steps to reproduce:**
1. First step
2. Second step
3. Third step (BUG)

**Expected Behavior:**

**Actual Behavior:**

**Log / Stack Trace of exceptions, errors, etc:**
