### ISSUE TITLE
Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by symphonicz** [jwplayer/jwplayer-sdk-android-demo#41]
hello, i try to create sample app using Android SDK

i press **HD button** to change **Quality** during video played till the end.

After video ended i press **replay button** to play video again the problem is appear 
**"Cannot read property 'file' of undefined"**

i don't know how to fix it. pls help

thanks.

**Comment by GMSyrimis** [comment]
@symphonicz This is an old thread, most likely resolved in the latest version of the SDK.

If you are still having trouble please provide the following in a new issue report:

**Issue Summary:**

**JWP SDK Ver #:**

**OS Version:** 

**Device make & model:**

**IDE:**

**Video or Screenshots:** 

**Demo App source code experiencing the issue:** 

**Steps to reproduce:**
1. First step
2. Second step
3. Third step (BUG)

**Expected Behavior:**

**Actual Behavior:**

**Log / Stack Trace of exceptions, errors, etc:**
