### ISSUE TITLE
JW Player Chromecast Not working

### ISSUE THREAD

**Issue by demo1232** [jwplayer/jwplayer-sdk-android-demo#42]
JW player chromecast button not showing in this demo.
JWPlayer chromecast functionality not working.

We have downloaded the sample app which you have given above Url and run successfully. But we are facing some problem to connect
1.We are not able to see MediaRouteButton above of the ActionBar also attached a screen shot.
2.We are not able to understand how to connect sample app to Android TV.
3.Is chrome cast device required to connect mobile app to the desktop?

Below is the URL that is using for reference:-
https://developer.jwplayer.com/sdk/android/docs/developer-guide/chromecast/getting-started/

Please help us ASAP.

**Comment by Digvesh** [comment]
I am getting error something like this, can you please help us what we have missed here

 D/ccl_VideoCastManager: [v2.9.1] attachMediaChannel()
 D/ccl_VideoCastManager: [v2.9.1] Registering MediaChannel namespace
 ***E/AudioAttributes: Invalid stream type -1 for AudioAttributes*
 *E/LICENSE ERROR: Your key edition FREE is not valid for the attempted action.***
 D/ccl_BaseCastManager: [v2.9.1] disconnectDevice(true,true)
 D/ccl_BaseCastManager: [v2.9.1] disconnectDevice() Disconnect Reason: Intentional disconnect
 D/ccl_BaseCastManager: [v2.9.1] mConnectionSuspended: false
 D/ccl_BaseCastManager: [v2.9.1] clearPersistedConnectionInfo(): Clearing persisted data for 0
 D/ccl_BaseCastManager: [v2.9.1] stopReconnectionService()
 D/ccl_VideoCastManager: [v2.9.1] trying to detach media channel
 D/ccl_BaseCastManager: [v2.9.1] Trying to disconnect
 D/ccl_BaseCastManager: [v2.9.1] disconnectDevice(): Setting route to default
 D/ccl_BaseCastManager: [v2.9.1] onDisconnected() reached
 D/ccl_VideoCastManager: [v2.9.1] updateMiniControllersVisibility() reached with visibility: false
 D/ccl_VideoCastManager: [v2.9.1] clearMediaSession()

**Comment by GMSyrimis** [comment]
This is an old thread and I will be closing it. However, if you are still having issues, always provide the following:

**Issue Summary:**

**JWP SDK Ver #:**

**OS Version:** 

**Device make & model:**

**IDE:**

**Video or Screenshots:** 

**Demo App source code experiencing the issue:** 

**Steps to reproduce:**
1. First step
2. Second step
3. Third step (BUG)

**Expected Behavior:**

**Actual Behavior:**

**Log / Stack Trace of exceptions, errors, etc:**
