### ISSUE TITLE
When I click on HD quality app crash 

### ISSUE THREAD

**Issue by iamrajendra** [jwplayer/jwplayer-sdk-android-demo#43]
jw player  is working fine. but when I pause the video and close the mobile screen. and again click on the HD quality option the app get crashed and  get following exception : 

```
                                E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.intellezy, PID: 9183
                                                             java.lang.IndexOutOfBoundsException: Index: 2, Size: 0

```
now the problem is  as follow : 
1. we are not getting any callback when clicked on HD Quality Button 
2. We are not getting the point of Exception. if we can get that , we  can manage it through  **try and catch block.** 
3.  when the app crash : 

```
@Override
    public void onQualityChange(int currentQuality) {

        Log.i(TAG, "onQualityChange: ");

    }

    @Override
    public void onQualityLevels(List<QualityLevel> levels) {

        Log.i(TAG, "onQualityLevels: ");

    }
```
We have these two callback but when we click on HD Quality we are not getting any response before app crash. 
![device-2017-09-11-144945](https://user-images.githubusercontent.com/17670029/30267648-dc9b08a4-9700-11e7-936f-967b04ff15d3.png)

**Comment by GMSyrimis** [comment]
@iamrajendra This is an old issue using an old version of our SDK. Try building with our latest SDK and if you are having trouble please provide the following:

**Issue Summary:**

**JWP SDK Ver #:**

**OS Version:** 

**Device make & model:**

**IDE:**

**Video or Screenshots:** 

**Demo App source code experiencing the issue:** 

**Steps to reproduce:**
1. First step
2. Second step
3. Third step (BUG)

**Expected Behavior:**

**Actual Behavior:**

**Log / Stack Trace of exceptions, errors, etc:**
