### ISSUE TITLE
JW player Issue of rendering

### ISSUE THREAD

**Issue by Digvesh** [jwplayer/jwplayer-sdk-android-demo#47]
I have created on JW Player in Activity A
Activity A has a button to moved on Activity B
Activity B has one more JW player 

Once i tap back on Activity B the Player Which is on Activity A is not rendering even it also missed contols.

This issue is also in demo code.
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'id-0' of undefined", source: http://intercept.jw//data/user/0/com.premiereradio.android.rushlimbaugh/files/jwplayer/jw_core/html5_provider_mobile.js (1)

Error in console.

Please suggest.

Thanks

**Comment by GMSyrimis** [comment]
@Digvesh This is an old thread. Try building with the latest SDK. If you are still having trouble, please provide the follwing:

**Issue Summary:**

**JWP SDK Ver #:**

**OS Version:** 

**Device make & model:**

**IDE:**

**Video or Screenshots:** 

**Demo App source code experiencing the issue:** 

**Steps to reproduce:**
1. First step
2. Second step
3. Third step (BUG)

**Expected Behavior:**

**Actual Behavior:**

**Log / Stack Trace of exceptions, errors, etc:**
