### ISSUE TITLE
Errors when building test app

### ISSUE THREAD

**Issue by andaaraus** [jwplayer/jwplayer-sdk-android-demo#54]
Trying to build the test app and currently having these errors:

Gradle tasks [clean, :app:assembleDebug]
/Users/eric/Desktop/jwplayer-sdk-android-demo-master/app/src/main/res/layout/custom_media_route_controller_controls_dialog.xml
Error:(36, 26) No resource found that matches the given name (at 'src' with value '@drawable/album_art_placeholder').
Error:(46, 22) No resource found that matches the given name (at 'src' with value '@drawable/ic_av_pause_light').
Error:(82, 32) No resource found that matches the given name (at 'textColor' with value '@color/ccl_mr_custom_line_1').
Error:(97, 32) No resource found that matches the given name (at 'textColor' with value '@color/ccl_mr_custom_line_2').
Error:(110, 23) No resource found that matches the given name (at 'text' with value '@string/ccl_no_media_info').
Error:(112, 28) No resource found that matches the given name (at 'textColor' with value '@color/ccl_mr_custom_line_1').
/Users/eric/Desktop/jwplayer-sdk-android-demo-master/app/build/intermediates/res/merged/debug/layout/custom_media_route_controller_controls_dialog.xml
Error:(36, 26) No resource found that matches the given name (at 'src' with value '@drawable/album_art_placeholder').
Error:(46, 22) No resource found that matches the given name (at 'src' with value '@drawable/ic_av_pause_light').
Error:(82, 32) No resource found that matches the given name (at 'textColor' with value '@color/ccl_mr_custom_line_1').
Error:(97, 32) No resource found that matches the given name (at 'textColor' with value '@color/ccl_mr_custom_line_2').
Error:(110, 23) No resource found that matches the given name (at 'text' with value '@string/ccl_no_media_info').
Error:(112, 28) No resource found that matches the given name (at 'textColor' with value '@color/ccl_mr_custom_line_1').
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
Information:BUILD FAILED
Information:Total time: 7.416 secs
Information:13 errors
Information:0 warnings
Information:See complete output in console

Thanks in advanced

**Comment by GMSyrimis** [comment]
@andaaraus Looks like you haven't imported certain components related to Chromecast:

`/Users/eric/Desktop/jwplayer-sdk-android-demo-master/app/src/main/res/layout/custom_media_route_controller_controls_dialog.xml`

This is an old thread, build with the latest demo app and if you are still having issues please provide the following:

**Issue Summary:**

**JWP SDK Ver #:**

**OS Version:** 

**Device make & model:**

**IDE:**

**Video or Screenshots:** 

**Demo App source code experiencing the issue:** 

**Steps to reproduce:**
1. First step
2. Second step
3. Third step (BUG)

**Expected Behavior:**

**Actual Behavior:**

**Log / Stack Trace of exceptions, errors, etc:**
