### ISSUE TITLE
Android: Image render issue with JWPlayer SDK v3.9.0

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [jwplayer/jwplayer-sdk-android-demo#95]
We are using JW player Android SDK v3.9.0 with minimum SDK v21 and target SDK v28.

We are displaying thumb of video (by setting .image) with below code, but URL starting with http is not working. Yes, it works with https. Look over below code and provide your feedback.

```
playlist.add(new PlaylistItem.Builder()
.image("Here http path not works but https works")
.file("Media URL")
.title("Title of Media")
.description("Discription of media")
.build());
```

**Comment by bluelabeldeveloper1** [comment]
Just checking, any updates here?

**Comment by mwaked** [comment]
I have the same issue? Any updates?

**Comment by GMSyrimis** [comment]
If you haven't resolved the issue yet, please contact support. They can help troubleshoot the issue. Closing this thread as it's fairly old. 

If it doesn't work with HTTP but works with HTTPS either you need to enable cleartext traffic on the device with a `network_config.xml` or the WebView that is loading the image is blocking the HTTP request because the WebView is HTTPS. Overall, we recommend you stick with HTTPS resources wherever possible.
